package sapient

import (
	"encoding/hex"
	"testing"
)

var (
	HEXEncoded       = "69b73efeba"
	Base64URLEncoded = "abc-_ro"
)

// testKeys is a collection for keys generated by PHP version of sapient
var testKeys = []string{
	"mZAy9XcqHdn36cEoG_0HHzzsECQYTo5FMSuov55X9gdbpxAUytVQJYHYAazMOO6iVQ0U5AiS_P7_iI_ebjVyow==",
	"W6cQFMrVUCWB2AGszDjuolUNFOQIkvz-_4iP3m41cqM=",
	"7vrdkjx4uF5cwpGJsKJIxJ4E_3D-6OXm",
	"JUtWIsmBwXpwCA17sysEJ5SfjqyPWI71NfIwGcoomGxD4kVkmlgiGTcZzHtMbFEGmBfVwV1hGEernES_zMdslg==",
	"Q-JFZJpYIhk3Gcx7TGxRBpgX1cFdYRhHq5xEv8zHbJY=",
	"H2VqrIxGdYwmLMJSpXTORjShbqvJS0If",
	"sU6_BRgzAshrWIm3cW3Uj0aUTNVJ7osVumO5vA2nC7ym6c1lTZGBuTvWdDbyTuxCrVEXVhB1BmDHKaPfYlJzxQ==",
	"punNZU2Rgbk71nQ28k7sQq1RF1YQdQZgxymj32JSc8U=",
	"G5fMsNUQEYuUf4b15h0mWsfxbjTOItqz",
	"DXJ0JaqLTM2ra_HQ7TgcRUXZZzI-doBly14jtaCDhgjPlociOATRJMkbArAhGM0YTgGj3o-hfS0EUGn9WqEI4A==",
	"z5aHIjgE0STJGwKwIRjNGE4Bo96PoX0tBFBp_VqhCOA=",
	"AxBt0VLu5Q-8xYYE4vUOckpLcO1Z_WiK",
	"hif8ITPZzhOmZmj_qKn3njVWimUWxQaDpHarkXGHeptO1z96SRk_af_n5r7D72zpkHMMr53wrapPjpBI1HS65w==",
	"Ttc_ekkZP2n_5-a-w-9s6ZBzDK-d8K2qT46QSNR0uuc=",
	"cUftiJJ-ddQUI7Q78YC_H481k3-AcCLD",
}

func TestBase64Url(t *testing.T) {

	for _, key := range testKeys {

		public, err := Base64UrlDecode(key)

		if err != nil {
			t.Error(err)
		}

		encodedKey := Base64UrlEncode(public)

		if key != encodedKey && key != encodedKey+"=" && key != encodedKey+"==" {
			t.Errorf("Failed to encode probably, original(%v) - generated(%v)", key, encodedKey)
		}
	}
}

/*
	Test base64url.Encode function using a hex encoded string corresponding to an Base64URLEncoded string.
	First we decode the hex encoded bytes and then run the encode function on this and check the result with the
	corresponding Base64url encoded data.
*/
func TestEncode(t *testing.T) {
	testBytes := make([]byte, len(HEXEncoded)/2)
	hex.Decode(testBytes, []byte(HEXEncoded))
	resultStr := Base64UrlEncode(testBytes)
	if Base64URLEncoded != resultStr {
		t.Errorf(Base64URLEncoded + " not equal with " + resultStr)
	}
}

/*
	Test base64url.Decode function using a hex encoded string corresponding to an Base64URLEncoded string.
	First we decode the Base64URLEncoded string checking the error condition so we have a correctly encoded string.
	Then we hex encode the result and check it against the corresponding hex encoded string.
*/
func TestDecode(t *testing.T) {
	resultBytes, err := Base64UrlDecode(Base64URLEncoded)
	if err != nil {
		t.Errorf("Could not decode Base64URLEncoded string: %v", err)
	}
	hexEncodedBytes := make([]byte, len(resultBytes)*2)
	hex.Encode(hexEncodedBytes, resultBytes)
	resultStr := string(hexEncodedBytes)
	if HEXEncoded != resultStr {
		t.Errorf(HEXEncoded + " not equal with " + resultStr)
	}

	// Should error when an illegal character is encountered.
	resultBytes, err = Base64UrlDecode(Base64URLEncoded + "+")
	if err == nil {
		t.Errorf("Should throw error when an illegal character is encountered.")
	}
}
